### ISSUE TITLE
Feature: Support opening multiple files

### ISSUE THREAD

**Issue by baest** [oalders/open-this#3]
This may be somewhat of the primary use case for Open::This, but it would be nice if OT could support opening more than one file at the time. Along with this could be possible to opening the files in a split view. I could provide a Pull request if this doesn't sound awful.

**Comment by baest** [comment]
I have thought more about it and I think you're right. OT is more for easily finding files or something in a file. The functionality I suggested will just complicate. If needed I think a wrapper around OT would be more helpful.

Thank you very much for your quick but very well thought through reply!

**Comment by oalders** [comment]
Sounds good.  To be clear, I wasn't saying that this is a bad idea, but just an idea that I hadn't considered.  If you do write a wrapper, I'd be interested to see what it looks like.

**Comment by baest** [comment]
Sure, I didn't understand you as saying it was a bad idea, but it made me reconsider whether or not it was good idea. Of course, I will do post the code if I get it done.
