### ISSUE TITLE
Find go test files with relative file paths

### ISSUE THREAD

**Issue by oalders** [oalders/open-this#30]
If I run `go test ./...` from a top level directory, the test failure output may refer to a filename without using its absolute path, as below:

```bash
=== RUN   TestRecordToString
--- FAIL: TestRecordToString (0.00s)
    mmdbinspect_test.go:78:
                Error Trace:    mmdbinspect_test.go:78
                Error:          "null" does not contain "London"
                Test:           TestRecordToString
```

`ot mmdbinspect_test.go:78` will not find anything in this case, since it needs to be looking in a subfolder.  We could special-case `.go` files for this.

**Comment by choroba** [comment]
I have no experience with go. What subfolder should it be looking in?

**Comment by choroba** [comment]
Yes, it is. Sorry, should have mentioned it right away. Thanks for the explanation.

**Comment by oalders** [comment]
Ok, that makes sense. 😄 There are also some `Perl::Critic` violations that could either be fixed or silenced with annotations, if you're looking for an easy win. It might also be possible to make the script run a touch faster via some profiling. Not too sure about that as it has generally been fast enough for me, but there could be something there as well.

There is also a bit of a gap in code coverage: https://app.codecov.io/gh/oalders/open-this/blob/master/lib/Open/This.pm

Also, not sure about the 5.37 failures. I'm guessing it may be too early to dive into those: http://www.cpantesters.org/cpan/report/b6d47134-1444-11ed-a232-7ebc93459d83

**Comment by choroba** [comment]
Something like #47?
