### ISSUE TITLE
Can't open Acme::Bleach... what am I doing wrong?

### ISSUE THREAD

**Issue by borisdaeppen** [oalders/open-this#8]
This opens source for `Test::More`
`user@host:~$ EDITOR=vim ot Test::More`

This gives an error
```
user@host:~$ EDITOR=vim ot Acme::Bleach
Cannot bleach '/home/bo/perl5/perlbrew/perls/perl-5.22.4/bin/ot'

```
`Acme::Bleach` is installed via `cpanm`
```
find . -name Bleach.pm
./perl5/perlbrew/perls/perl-5.22.4/lib/site_perl/5.22.4/Acme/Bleach.pm
```

**Comment by oalders** [comment]
Interesting.  This error looks to be from https://metacpan.org/source/DCONWAY/Acme-Bleach-1.150/lib/Acme/Bleach.pm#L15

I *think* what is happening is that
* `require_module` is called (we use this to locate `Acme::Bleach` on disk)
* this causes `Acme::Bleach` to run itself on the caller
* `Acme::Bleach` cannot overwrite `ot` with the bleached output and returns an error

**Comment by oalders** [comment]
It's an interesting case for sure.  I'm going to re-open this ticket because I think the error message can be improved.  As it stands, it's very confusing.

**Comment by jjatria** [comment]
Module::Util can be used to find the file without using require, which would fix this. I'm not sure what ramifications it might have, so we might want to be careful. But it still passes tests, and makes it work with Acme::Bleach.

What do you think?

**Comment by oalders** [comment]
Actually, not using `require` would be great.  I think we could just try it and see how it works in the real world.  I don't have a lot of time at my machine right now, but I'd merge and release a PR for this.

**Comment by oalders** [comment]
If anyone had time to add a regression test that runs only when `Acme::Bleach` is already installed, that would be useful. ie: `use Test::Needs 'Acme::Bleach'` . I'll create an issue for it.
